### ISSUE TITLE
If there have keyboard shortcuts would be better

### ISSUE THREAD

**Issue by yinheli** [Crasnam/vscode-elasticdeveloper#2]

**Comment by Crasnam** [comment]
At the moment you can use alt+enter to run all queries, if you don’t like that key binding you can change it in the keyboard shortcuts section in Visual Studio Code, look for command "elasticdeveloper.query.runall.fromTextEditor".

I will look into to adding more keyboard shortcuts and also some "command cleaning" when I’m done with the next feature: intellisense support. 

If you or anyone else has any suggestions for much needed keyboard shortcuts, please tell. 😊

Best regards
Crasnam

**Comment by yinheli** [comment]
Thanks
