### ISSUE TITLE
Add formatters for es* files 

### ISSUE THREAD

**Issue by SavvySkylark** [Crasnam/vscode-elasticdeveloper#8]
This extension is great and would be even better if the es file extensions worked with the auto-format on vscode.

**Comment by SavvySkylark** [comment]
This extension is great and would be perfect for me if I could do auto format.

**Comment by Crasnam** [comment]
Hi @SavvySkylark 
Thanks for the suggestion. I have added support for _.es_ file extensions and sent out a new release to the marketplace. Please verify that it works for you.

Best regards
Crasnam

**Comment by vd3d** [comment]
I can't make it work, how can I format the code please ?

When I try, it say "no formatted for es file" :-(
